print("Rishabh")
print("324, South Park Road")
print("Thornhill, ON L3T7W1")
print()
print("19th March, 2020")
print()
print("Pawel Leja")
print("TITLE")
print("St Robert CHS")
print("8101 Leslie St")
print("Thornhill, ON LT37P4")